language: r
cache: packages

r:
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - ade4
  - cclust
  - bipartite
  - labdsv
  - car
  - ellipse
  - smacof
  - coda
  - maptools
  - ape
  - picante

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - tlmgr install sidecap

r_build_args: " --compact-vignettes=gs+qpdf"

notifications:
  email:
    on_success: change
    on_failure: always

